from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    KeepTogether,
    Image,
)
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from datetime import datetime
from src.logger.logger import Logger

logger = Logger().setup_logs()


class ReportGenerator:
    def __init__(self, net_data, pro_data, sys_data, username):
        self.username = username
        self.styles = getSampleStyleSheet()
        self.styles.add(
            ParagraphStyle(
                name="FooterStyle", parent=self.styles["Normal"], alignment=1
            )
        )
        self.styles.add(
            ParagraphStyle(name="TitleStyle", parent=self.styles["Title"], alignment=1)
        )
        self.styles.add(
            ParagraphStyle(name="InfoStyle", parent=self.styles["Normal"], alignment=1)
        )
        self.styles.add(
            ParagraphStyle(
                name="NormalStyle", parent=self.styles["BodyText"], alignment=0
            )
        )
        self.styles.add(
            ParagraphStyle(
                name="CenteredHeading1", parent=self.styles["Heading1"], alignment=1
            )
        )
        self.styles.add(
            ParagraphStyle(
                name="CenteredHeading2", parent=self.styles["Heading2"], alignment=0
            )
        )
        self._gen_report(sys_data, pro_data, net_data)

    def _footer(self, canvas, doc):
        footer_para = Paragraph(
            "Made with ♥ by Abhishek Tiwari", self.styles["FooterStyle"]
        )
        w, h = footer_para.wrap(doc.width, doc.bottomMargin)
        footer_para.drawOn(canvas, doc.leftMargin, 10)

    def _title_page(self):
        story = []
        story.append(Spacer(1, 300))
        story.append(Paragraph("System Analysis Report", self.styles["TitleStyle"]))
        story.append(Spacer(1, 6))
        story.append(
            Paragraph(
                f"Report Generated by: TrackerApp Application", self.styles["InfoStyle"]
            )
        )
        story.append(Spacer(1, 5))
        story.append(
            Paragraph(
                f"Date: {datetime.today().strftime('%B %d, %Y')}",
                self.styles["InfoStyle"],
            )
        )
        story.append(PageBreak())
        logger.info(f"Title Page Data Created for PDF.")
        return story

    def _report(self, sys_data, pro_data, net_data):
        try:
            story = []
            story.append(Paragraph("SYSTEM ANALYSIS", self.styles["CenteredHeading1"]))
            story.append(Spacer(1, 12))
            plot_title = {
                "cpu_load_trend_over_time": "CPU Load Trend Over Time",
                "memory_usage_trend_over_time": "Memory Usage Trend Over Time",
                "battery_pct_over_time": "Battery Percentage Trend Over Time",
            }
            for key, title in plot_title.items():
                if key in sys_data:
                    block = KeepTogether(
                        [
                            Paragraph(f"{title}", self.styles["CenteredHeading2"]),
                            Spacer(1, 6),
                            Image(sys_data[key], width=6.0 * inch, height=3.5 * inch),
                            Spacer(1, 12),
                        ]
                    )
                    story.append(block)
            story.append(Spacer(1, 12))
            story.append(Paragraph("PROCESS ANALYSIS", self.styles["CenteredHeading1"]))
            story.append(Spacer(1, 12))
            plot_title = {
                "top_cpu_process": "CPU for Processes",
                "top_memory_process": "Memory for Processes",
            }
            for key, title in plot_title.items():
                if key in pro_data:
                    block = KeepTogether(
                        [
                            Paragraph(f"{title}", self.styles["CenteredHeading2"]),
                            Spacer(1, 6),
                            Image(pro_data[key], width=6.0 * inch, height=3.5 * inch),
                            Spacer(1, 12),
                        ]
                    )
                    story.append(block)
            story.append(Spacer(1, 12))
            story.append(Paragraph("NETWORK ANALYSIS", self.styles["CenteredHeading1"]))
            story.append(Spacer(1, 12))
            plot_title = {
                "download_speed_trend": "Download Speed over Time",
                "upload_speed_trend": "Upload Speed over Time",
                "byte_rate_trend": "Byte Rate Trend",
            }
            for key, title in plot_title.items():
                if key in net_data:
                    block = KeepTogether(
                        [
                            Paragraph(f"{title}", self.styles["CenteredHeading2"]),
                            Spacer(1, 6),
                            Image(net_data[key], width=6.0 * inch, height=3.5 * inch),
                            Spacer(1, 12),
                        ]
                    )
                    story.append(block)
            logger.info(f"Report Data is Created for the PDF.")
            return story
        except Exception as e:
            logger.exception(f"Got Error While Working on report geneartion: {e}")

    def _gen_report(self, sys_data, pro_data, net_data):
        try:
            story = self._title_page() + self._report(sys_data, pro_data, net_data)
            doc = SimpleDocTemplate(f"Report_{self.username}.pdf", pagesize=A4)
            logger.info(f"Writing Data to PDF.")
            doc.build(story, onFirstPage=self._footer, onLaterPages=self._footer)
        except Exception as e:
            logger.exception(f"Got Error While Creating the PDF: {e}")
